AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Project A with ECS, MySQL, and Fargate

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: ProjectA-VPC

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ProjectA-Cluster

  MySQLContainer:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: ProjectA-MySQL
      ContainerDefinitions:
        - Name: MySQL
          Image: mysql:5.7
          Memory: 1024
          Cpu: 512
          Essential: true
          PortMappings:
            - ContainerPort: 3306

  FargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref MySQLContainer
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref SecurityGroup
          AssignPublicIp: ENABLED

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC

  ECSClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster